### ISSUE TITLE
More descriptive readme with use cases

### ISSUE THREAD

**Issue by msn0** [msn0/wilson-score-interval#4]
The Wilson score interval might be ambigious to the people who doesn't know this scoring technique. Readme should describe what it does, what for it's used (e.g. to sort comments, reviews) and to what extent it's different/better from other sorting methods.

**Comment by csjiang** [comment]
Hey @msn0 , I am going to take a stab at this.

**Comment by msn0** [comment]
https://github.com/msn0/wilson-score-interval/pull/5
